# Generated by Django 4.1.4 on 2022-12-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('tag', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'classrooms',
            },
        ),
    ]
