# Generated by Django 4.1.4 on 2022-12-08 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='portafolio',
            table='portafolios',
        ),
    ]
