# Generated by Django 4.1.3 on 2022-12-12 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_portafolio_idusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portafolio',
            name='idUsuario',
        ),
    ]
